# Generated by Django 4.2.5 on 2023-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название альбома'),
        ),
    ]
