version: "3.9"

volumes:
  postgres_data:
  static:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: /backend
    env_file: /backend/albums_and_songs/.env
    command: gunicorn albums_and_songs.wsgi:application --bind 0:8000
    volumes:
      - static:/app/static/
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:13.4-alpine"
    env_file: /backend/albums_and_songs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
